Fix NoSuchMethodError with DiscordSRV hook
Caused by: java.lang.NoSuchMethodError: github.scarsz.discordsrv.dependencies.jda.core.entities.Message.getContent()Ljava/lang/String;